package entity;

public enum Genre {
	//Music
	POP, ALTERNATIVE_ROCK, METAL, HIP_HOP, DANCE, JAZZ, COUNTRY,
	
	//Book
	DRAMA, NON_FICTION, COMEDY, REALISTIC_FICTION, SERIES, ROMANCE,
	
	//Movie
	SCI_FI, WESTERN, DOCUMENTARY, ACTION, ADVENTURE, CRIME, HISTORICAL, HORROR, MUSICAL, WAR, CHILDRENS_SERIES,

}
